name: "pre-release"
on:
  push:
    branches:
      - "master"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@8cec54fd76f4690a8f4859843820a98cb0b6bd9b"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: false
          title: "dev"
          files: |
            action.yml
            *.sh
